/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as MethodRouteImport } from './routes/method'
import { Route as CycleIdRouteImport } from './routes/cycle.$id'
import { Route as ProbeIdRouteImport } from './routes/probe.$id'
import { Route as RouteIdRouteImport } from './routes/route.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodRoute = MethodRouteImport.update({
  id: '/method',
  path: '/method',
  getParentRoute: () => rootRouteImport,
} as any)
const CycleIdRoute = CycleIdRouteImport.update({
  id: '/cycle/$id',
  path: '/cycle/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProbeIdRoute = ProbeIdRouteImport.update({
  id: '/probe/$id',
  path: '/probe/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RouteIdRoute = RouteIdRouteImport.update({
  id: '/route/$id',
  path: '/route/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/console': typeof ConsoleRoute
  '/method': typeof MethodRoute
  '/cycle/$id': typeof CycleIdRoute
  '/probe/$id': typeof ProbeIdRoute
  '/route/$id': typeof RouteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/console': typeof ConsoleRoute
  '/method': typeof MethodRoute
  '/cycle/$id': typeof CycleIdRoute
  '/probe/$id': typeof ProbeIdRoute
  '/route/$id': typeof RouteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/console': typeof ConsoleRoute
  '/method': typeof MethodRoute
  '/cycle/$id': typeof CycleIdRoute
  '/probe/$id': typeof ProbeIdRoute
  '/route/$id': typeof RouteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/console' | '/method' | '/cycle/$id' | '/probe/$id' | '/route/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/console' | '/method' | '/cycle/$id' | '/probe/$id' | '/route/$id'
  id:
    | '__root__'
    | '/'
    | '/console'
    | '/method'
    | '/cycle/$id'
    | '/probe/$id'
    | '/route/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsoleRoute: typeof ConsoleRoute
  MethodRoute: typeof MethodRoute
  CycleIdRoute: typeof CycleIdRoute
  ProbeIdRoute: typeof ProbeIdRoute
  RouteIdRoute: typeof RouteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/method': {
      id: '/method'
      path: '/method'
      fullPath: '/method'
      preLoaderRoute: typeof MethodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cycle/$id': {
      id: '/cycle/$id'
      path: '/cycle/$id'
      fullPath: '/cycle/$id'
      preLoaderRoute: typeof CycleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/probe/$id': {
      id: '/probe/$id'
      path: '/probe/$id'
      fullPath: '/probe/$id'
      preLoaderRoute: typeof ProbeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/route/$id': {
      id: '/route/$id'
      path: '/route/$id'
      fullPath: '/route/$id'
      preLoaderRoute: typeof RouteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsoleRoute: ConsoleRoute,
  MethodRoute: MethodRoute,
  CycleIdRoute: CycleIdRoute,
  ProbeIdRoute: ProbeIdRoute,
  RouteIdRoute: RouteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
