// Generates typed ABIs from `forge build` output.
// The API must never hand-declare an ABI: a signature that drifts from the
// deployed contract fails at broadcast, not at compile time.
import { readFileSync, writeFileSync, existsSync } from 'node:fs'

const CONTRACTS = ['ProbeLedger', 'RouteRegistry', 'Scorer'] as const
const OUT = new URL('../../../contracts/out/', import.meta.url).pathname

let file = '// GENERATED by packages/abi/scripts/gen.ts, do not edit.\n'
file += '// Regenerate with: forge build && bun run --filter @gokuin/abi gen\n\n'

for (const name of CONTRACTS) {
  const p = `${OUT}${name}.sol/${name}.json`
  if (!existsSync(p)) throw new Error(`missing ${p}: run 'forge build' in contracts/ first`)
  const { abi } = JSON.parse(readFileSync(p, 'utf8'))
  file += `export const ${name}Abi = ${JSON.stringify(abi, null, 2)} as const\n\n`
}
writeFileSync(new URL('../src/index.ts', import.meta.url).pathname, file)
console.log(`wrote ${CONTRACTS.length} ABIs`)
