// GENERATED by packages/abi/scripts/gen.ts, do not edit.
// Regenerate with: forge build && bun run --filter @gokuin/abi gen

export const ProbeLedgerAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "prober_",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "commitCycle",
    "inputs": [
      {
        "name": "cycleId",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "scheduleHash",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "count",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "cycles",
    "inputs": [
      {
        "name": "",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "outputs": [
      {
        "name": "scheduleHash",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "salt",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "committedCount",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "publishedCount",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "committedAt",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "revealed",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "integrity",
    "inputs": [
      {
        "name": "cycleId",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "outputs": [
      {
        "name": "committed",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "published",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "intact",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "prober",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "record",
    "inputs": [
      {
        "name": "cycleId",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "row",
        "type": "tuple",
        "internalType": "struct ProbeLedger.Row",
        "components": [
          {
            "name": "mainnetTxHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "submittedBlock",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "includedBlock",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "leakedAtBlock",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "extractedWei",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "simOut",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "realOut",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "routeId",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "cycleId",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "sandwiched",
            "type": "bool",
            "internalType": "bool"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "rowId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "revealCycle",
    "inputs": [
      {
        "name": "cycleId",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "routeIds",
        "type": "uint32[]",
        "internalType": "uint32[]"
      },
      {
        "name": "slots",
        "type": "uint64[]",
        "internalType": "uint64[]"
      },
      {
        "name": "salt",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "rowCount",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "rows",
    "inputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "mainnetTxHash",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "submittedBlock",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "includedBlock",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "leakedAtBlock",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "extractedWei",
        "type": "uint128",
        "internalType": "uint128"
      },
      {
        "name": "simOut",
        "type": "uint128",
        "internalType": "uint128"
      },
      {
        "name": "realOut",
        "type": "uint128",
        "internalType": "uint128"
      },
      {
        "name": "routeId",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "cycleId",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "sandwiched",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "rowsByRoute",
    "inputs": [
      {
        "name": "routeId",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256[]",
        "internalType": "uint256[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "event",
    "name": "CycleCommitted",
    "inputs": [
      {
        "name": "cycleId",
        "type": "uint16",
        "indexed": true,
        "internalType": "uint16"
      },
      {
        "name": "scheduleHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "count",
        "type": "uint16",
        "indexed": false,
        "internalType": "uint16"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "CycleRevealed",
    "inputs": [
      {
        "name": "cycleId",
        "type": "uint16",
        "indexed": true,
        "internalType": "uint16"
      },
      {
        "name": "salt",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "published",
        "type": "uint16",
        "indexed": false,
        "internalType": "uint16"
      },
      {
        "name": "intact",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "RowRecorded",
    "inputs": [
      {
        "name": "cycleId",
        "type": "uint16",
        "indexed": true,
        "internalType": "uint16"
      },
      {
        "name": "routeId",
        "type": "uint32",
        "indexed": true,
        "internalType": "uint32"
      },
      {
        "name": "rowId",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "mainnetTxHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "AlreadyRevealed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BadSalt",
    "inputs": []
  },
  {
    "type": "error",
    "name": "CycleExists",
    "inputs": []
  },
  {
    "type": "error",
    "name": "CycleUnknown",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotProber",
    "inputs": []
  }
] as const

export const RouteRegistryAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "scorer_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "ensRegistry_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "parentNode_",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "ensRegistry",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "nodeOf",
    "inputs": [
      {
        "name": "",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "parentNode",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "registerRoute",
    "inputs": [
      {
        "name": "routeId",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "label",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [
      {
        "name": "node",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "routeOfNode",
    "inputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "scorer",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "setScore",
    "inputs": [
      {
        "name": "routeId",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "key",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "value",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "text",
    "inputs": [
      {
        "name": "node",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "key",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "string",
        "internalType": "string"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "event",
    "name": "RouteRegistered",
    "inputs": [
      {
        "name": "routeId",
        "type": "uint32",
        "indexed": true,
        "internalType": "uint32"
      },
      {
        "name": "label",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      },
      {
        "name": "node",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ScoreWritten",
    "inputs": [
      {
        "name": "routeId",
        "type": "uint32",
        "indexed": true,
        "internalType": "uint32"
      },
      {
        "name": "key",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      },
      {
        "name": "value",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "EmptyLabel",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotScorer",
    "inputs": []
  },
  {
    "type": "error",
    "name": "RouteAlreadyRegistered",
    "inputs": []
  },
  {
    "type": "error",
    "name": "RouteUnknown",
    "inputs": []
  }
] as const

export const ScorerAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "creForwarder_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "registry_",
        "type": "address",
        "internalType": "contract RouteRegistry"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "creForwarder",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "registry",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract RouteRegistry"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "submitScore",
    "inputs": [
      {
        "name": "routeId",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "leakBps",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "sandwichBps",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "medianDelay",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "composite",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "probes",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "lastCycle",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "evidenceURI",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "Scored",
    "inputs": [
      {
        "name": "routeId",
        "type": "uint32",
        "indexed": true,
        "internalType": "uint32"
      },
      {
        "name": "leakBps",
        "type": "uint16",
        "indexed": false,
        "internalType": "uint16"
      },
      {
        "name": "sandwichBps",
        "type": "uint16",
        "indexed": false,
        "internalType": "uint16"
      },
      {
        "name": "medianDelay",
        "type": "uint16",
        "indexed": false,
        "internalType": "uint16"
      },
      {
        "name": "composite",
        "type": "uint16",
        "indexed": false,
        "internalType": "uint16"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "NotCRE",
    "inputs": []
  }
] as const

