// docs/metrics.md is generated from packages/core/src/metrics.ts so the document
// cannot describe a metric the code does not implement. Same property the
// /method page has: definitions are read from the source, never restated.
//
//   bun run scripts/gen-metrics-doc.ts
import { readFileSync, writeFileSync } from 'node:fs'

const src = readFileSync('packages/core/src/metrics.ts', 'utf8')

// Pull each /** ... */ block that immediately precedes an exported function.
const blocks = [...src.matchAll(/\/\*\*([\s\S]*?)\*\/\s*export function (\w+)([^{]*)\{/g)]

const body = blocks
  .map(([, comment, name, sig]) => {
    const prose = comment
      .split('\n')
      .map(l => l.replace(/^\s*\*ic?\s?/, '').replace(/^\s*\*\s?/, ''))
      .join('\n')
      .trim()
    return `### \`${name}\`\n\n${prose}\n\n\`\`\`ts\nexport function ${name}${sig.trim()}\n\`\`\`\n`
  })
  .join('\n')

const provenance = src.match(/export const PROVENANCE = \{([\s\S]*?)\} as const/)?.[1] ?? ''
const rows = [...provenance.matchAll(/(\w+):\s*'(\w+)',?\s*(?:\/\/\s*(.*))?/g)]
  .map(([, k, v, note]) => `| \`${k}\` | **${v}** | ${note ?? ''} |`)
  .join('\n')

const min = src.match(/MIN_LISTENER_AGREEMENT = (\d+)/)?.[1] ?? '?'

writeFileSync(
  'docs/metrics.md',
  `# Measurement definitions

<!-- GENERATED by scripts/gen-metrics-doc.ts from packages/core/src/metrics.ts.
     Do not edit. Regenerate with: bun run scripts/gen-metrics-doc.ts -->

These are the definitions the contracts, the API, the MCP server and the web UI all
compile against. They live in one file, \`packages/core/src/metrics.ts\`, and this
document is generated from it — so a metric described here is a metric the code
implements, and a change to one is a change to both.

A leak is claimed only on agreement from **${min}** independent signed listeners.

## Provenance

Which figures anyone can re-derive from public data, and which rest on an
observation only Gokuin made. Five of six are public; the sixth is cross-checkable
against third-party mempool archives.

| Metric | Provenance | Note |
|---|---|---|
${rows}

## Definitions

${body}
## Where the arithmetic is pinned

\`packages/core/test/sandwich-fixture.test.ts\` and \`contracts/test/ForkDerive.t.sol\`
consume the same verified historical sandwich and must agree on \`extractedWei\`.
If the contract and the API disagree about what a sandwich cost, the project has
no product — so the disagreement is made to fail a test rather than surface in
production.
`,
)
console.log('wrote docs/metrics.md')
